version: '3'

services:
  server:
    build: .
    ports:
      - "8080:8080"  # Main server port
      - "9090:9090"  # Metrics port
    environment:
      - PORT=8080
      - METRICS_PORT=9090
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 