// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protogen/mcp/annotations.proto

package mcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_internal_protogen_mcp_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "mcp.annotations.mcp_service",
		Tag:           "varint,50000,opt,name=mcp_service",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "mcp.annotations.mcp_version",
		Tag:           "bytes,50001,opt,name=mcp_version",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "mcp.annotations.mcp_type",
		Tag:           "bytes,50002,opt,name=mcp_type",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "mcp.annotations.mcp_resource_service",
		Tag:           "varint,50003,opt,name=mcp_resource_service",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "mcp.annotations.mcp_resource_base_uri",
		Tag:           "bytes,50004,opt,name=mcp_resource_base_uri",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50006,
		Name:          "mcp.annotations.mcp_server_description",
		Tag:           "bytes,50006,opt,name=mcp_server_description",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "mcp.annotations.mcp_tool",
		Tag:           "varint,50000,opt,name=mcp_tool",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "mcp.annotations.mcp_tool_description",
		Tag:           "bytes,50001,opt,name=mcp_tool_description",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "mcp.annotations.mcp_tool_title",
		Tag:           "bytes,50002,opt,name=mcp_tool_title",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "mcp.annotations.mcp_tool_read_only",
		Tag:           "varint,50003,opt,name=mcp_tool_read_only",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "mcp.annotations.mcp_tool_destructive",
		Tag:           "varint,50004,opt,name=mcp_tool_destructive",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "mcp.annotations.mcp_tool_idempotent",
		Tag:           "varint,50005,opt,name=mcp_tool_idempotent",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50006,
		Name:          "mcp.annotations.mcp_tool_open_world",
		Tag:           "varint,50006,opt,name=mcp_tool_open_world",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "mcp.annotations.mcp_path_param",
		Tag:           "varint,50000,opt,name=mcp_path_param",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "mcp.annotations.mcp_query_param",
		Tag:           "varint,50001,opt,name=mcp_query_param",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "mcp.annotations.mcp_resource_uri",
		Tag:           "varint,50002,opt,name=mcp_resource_uri",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "mcp.annotations.mcp_field_description",
		Tag:           "bytes,50003,opt,name=mcp_field_description",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "mcp.annotations.mcp_required",
		Tag:           "varint,50004,opt,name=mcp_required",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50005,
		Name:          "mcp.annotations.mcp_validation_pattern",
		Tag:           "bytes,50005,opt,name=mcp_validation_pattern",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50006,
		Name:          "mcp.annotations.mcp_validation_message",
		Tag:           "bytes,50006,opt,name=mcp_validation_message",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "mcp.annotations.mcp_resource_template_message",
		Tag:           "varint,50000,opt,name=mcp_resource_template_message",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "mcp.annotations.mcp_uri_template",
		Tag:           "bytes,50001,opt,name=mcp_uri_template",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "mcp.annotations.mcp_template_description",
		Tag:           "bytes,50002,opt,name=mcp_template_description",
		Filename:      "internal/protogen/mcp/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Basic MCP service configuration
	//
	// optional bool mcp_service = 50000;
	E_McpService = &file_internal_protogen_mcp_annotations_proto_extTypes[0]
	// optional string mcp_version = 50001;
	E_McpVersion = &file_internal_protogen_mcp_annotations_proto_extTypes[1]
	// optional string mcp_type = 50002;
	E_McpType = &file_internal_protogen_mcp_annotations_proto_extTypes[2]
	// Resource configuration
	//
	// optional bool mcp_resource_service = 50003;
	E_McpResourceService = &file_internal_protogen_mcp_annotations_proto_extTypes[3]
	// optional string mcp_resource_base_uri = 50004;
	E_McpResourceBaseUri = &file_internal_protogen_mcp_annotations_proto_extTypes[4]
	// Description
	//
	// optional string mcp_server_description = 50006;
	E_McpServerDescription = &file_internal_protogen_mcp_annotations_proto_extTypes[5]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Basic MCP method configuration
	//
	// optional bool mcp_tool = 50000;
	E_McpTool = &file_internal_protogen_mcp_annotations_proto_extTypes[6]
	// Description
	//
	// optional string mcp_tool_description = 50001;
	E_McpToolDescription = &file_internal_protogen_mcp_annotations_proto_extTypes[7]
	// Tool annotations
	// Human-readable title for the tool
	//
	// optional string mcp_tool_title = 50002;
	E_McpToolTitle = &file_internal_protogen_mcp_annotations_proto_extTypes[8]
	// If true, the tool does not modify its environment
	//
	// optional bool mcp_tool_read_only = 50003;
	E_McpToolReadOnly = &file_internal_protogen_mcp_annotations_proto_extTypes[9]
	// If true, the tool may perform destructive updates
	//
	// optional bool mcp_tool_destructive = 50004;
	E_McpToolDestructive = &file_internal_protogen_mcp_annotations_proto_extTypes[10]
	// If true, repeated calls with same args have no additional effect
	//
	// optional bool mcp_tool_idempotent = 50005;
	E_McpToolIdempotent = &file_internal_protogen_mcp_annotations_proto_extTypes[11]
	// If true, tool interacts with external entities
	//
	// optional bool mcp_tool_open_world = 50006;
	E_McpToolOpenWorld = &file_internal_protogen_mcp_annotations_proto_extTypes[12]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Parameter types
	//
	// optional bool mcp_path_param = 50000;
	E_McpPathParam = &file_internal_protogen_mcp_annotations_proto_extTypes[13]
	// optional bool mcp_query_param = 50001;
	E_McpQueryParam = &file_internal_protogen_mcp_annotations_proto_extTypes[14]
	// optional bool mcp_resource_uri = 50002;
	E_McpResourceUri = &file_internal_protogen_mcp_annotations_proto_extTypes[15]
	// Field properties
	//
	// optional string mcp_field_description = 50003;
	E_McpFieldDescription = &file_internal_protogen_mcp_annotations_proto_extTypes[16]
	// optional bool mcp_required = 50004;
	E_McpRequired = &file_internal_protogen_mcp_annotations_proto_extTypes[17]
	// optional string mcp_validation_pattern = 50005;
	E_McpValidationPattern = &file_internal_protogen_mcp_annotations_proto_extTypes[18]
	// optional string mcp_validation_message = 50006;
	E_McpValidationMessage = &file_internal_protogen_mcp_annotations_proto_extTypes[19]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Resource template configuration
	//
	// optional bool mcp_resource_template_message = 50000;
	E_McpResourceTemplateMessage = &file_internal_protogen_mcp_annotations_proto_extTypes[20]
	// optional string mcp_uri_template = 50001;
	E_McpUriTemplate = &file_internal_protogen_mcp_annotations_proto_extTypes[21]
	// optional string mcp_template_description = 50002;
	E_McpTemplateDescription = &file_internal_protogen_mcp_annotations_proto_extTypes[22]
)

var File_internal_protogen_mcp_annotations_proto protoreflect.FileDescriptor

const file_internal_protogen_mcp_annotations_proto_rawDesc = "" +
	"\n" +
	"'internal/protogen/mcp/annotations.proto\x12\x0fmcp.annotations\x1a google/protobuf/descriptor.proto:B\n" +
	"\vmcp_service\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\bR\n" +
	"mcpService:B\n" +
	"\vmcp_version\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\tR\n" +
	"mcpVersion:<\n" +
	"\bmcp_type\x12\x1f.google.protobuf.ServiceOptions\x18҆\x03 \x01(\tR\amcpType:S\n" +
	"\x14mcp_resource_service\x12\x1f.google.protobuf.ServiceOptions\x18ӆ\x03 \x01(\bR\x12mcpResourceService:T\n" +
	"\x15mcp_resource_base_uri\x12\x1f.google.protobuf.ServiceOptions\x18Ԇ\x03 \x01(\tR\x12mcpResourceBaseUri:W\n" +
	"\x16mcp_server_description\x12\x1f.google.protobuf.ServiceOptions\x18ֆ\x03 \x01(\tR\x14mcpServerDescription:;\n" +
	"\bmcp_tool\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\bR\amcpTool:R\n" +
	"\x14mcp_tool_description\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x12mcpToolDescription:F\n" +
	"\x0emcp_tool_title\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\tR\fmcpToolTitle:M\n" +
	"\x12mcp_tool_read_only\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\bR\x0fmcpToolReadOnly:R\n" +
	"\x14mcp_tool_destructive\x12\x1e.google.protobuf.MethodOptions\x18Ԇ\x03 \x01(\bR\x12mcpToolDestructive:P\n" +
	"\x13mcp_tool_idempotent\x12\x1e.google.protobuf.MethodOptions\x18Ն\x03 \x01(\bR\x11mcpToolIdempotent:O\n" +
	"\x13mcp_tool_open_world\x12\x1e.google.protobuf.MethodOptions\x18ֆ\x03 \x01(\bR\x10mcpToolOpenWorld:E\n" +
	"\x0emcp_path_param\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\bR\fmcpPathParam:G\n" +
	"\x0fmcp_query_param\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\rmcpQueryParam:I\n" +
	"\x10mcp_resource_uri\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\x0emcpResourceUri:S\n" +
	"\x15mcp_field_description\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\tR\x13mcpFieldDescription:B\n" +
	"\fmcp_required\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\bR\vmcpRequired:U\n" +
	"\x16mcp_validation_pattern\x12\x1d.google.protobuf.FieldOptions\x18Ն\x03 \x01(\tR\x14mcpValidationPattern:U\n" +
	"\x16mcp_validation_message\x12\x1d.google.protobuf.FieldOptions\x18ֆ\x03 \x01(\tR\x14mcpValidationMessage:d\n" +
	"\x1dmcp_resource_template_message\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\bR\x1amcpResourceTemplateMessage:K\n" +
	"\x10mcp_uri_template\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\tR\x0emcpUriTemplate:[\n" +
	"\x18mcp_template_description\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\tR\x16mcpTemplateDescriptionB:Z8github.com/omrikiei/protoc-gen-mcp/internal/protogen/mcpb\x06proto3"

var file_internal_protogen_mcp_annotations_proto_goTypes = []any{
	(*descriptorpb.ServiceOptions)(nil), // 0: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_internal_protogen_mcp_annotations_proto_depIdxs = []int32{
	0,  // 0: mcp.annotations.mcp_service:extendee -> google.protobuf.ServiceOptions
	0,  // 1: mcp.annotations.mcp_version:extendee -> google.protobuf.ServiceOptions
	0,  // 2: mcp.annotations.mcp_type:extendee -> google.protobuf.ServiceOptions
	0,  // 3: mcp.annotations.mcp_resource_service:extendee -> google.protobuf.ServiceOptions
	0,  // 4: mcp.annotations.mcp_resource_base_uri:extendee -> google.protobuf.ServiceOptions
	0,  // 5: mcp.annotations.mcp_server_description:extendee -> google.protobuf.ServiceOptions
	1,  // 6: mcp.annotations.mcp_tool:extendee -> google.protobuf.MethodOptions
	1,  // 7: mcp.annotations.mcp_tool_description:extendee -> google.protobuf.MethodOptions
	1,  // 8: mcp.annotations.mcp_tool_title:extendee -> google.protobuf.MethodOptions
	1,  // 9: mcp.annotations.mcp_tool_read_only:extendee -> google.protobuf.MethodOptions
	1,  // 10: mcp.annotations.mcp_tool_destructive:extendee -> google.protobuf.MethodOptions
	1,  // 11: mcp.annotations.mcp_tool_idempotent:extendee -> google.protobuf.MethodOptions
	1,  // 12: mcp.annotations.mcp_tool_open_world:extendee -> google.protobuf.MethodOptions
	2,  // 13: mcp.annotations.mcp_path_param:extendee -> google.protobuf.FieldOptions
	2,  // 14: mcp.annotations.mcp_query_param:extendee -> google.protobuf.FieldOptions
	2,  // 15: mcp.annotations.mcp_resource_uri:extendee -> google.protobuf.FieldOptions
	2,  // 16: mcp.annotations.mcp_field_description:extendee -> google.protobuf.FieldOptions
	2,  // 17: mcp.annotations.mcp_required:extendee -> google.protobuf.FieldOptions
	2,  // 18: mcp.annotations.mcp_validation_pattern:extendee -> google.protobuf.FieldOptions
	2,  // 19: mcp.annotations.mcp_validation_message:extendee -> google.protobuf.FieldOptions
	3,  // 20: mcp.annotations.mcp_resource_template_message:extendee -> google.protobuf.MessageOptions
	3,  // 21: mcp.annotations.mcp_uri_template:extendee -> google.protobuf.MessageOptions
	3,  // 22: mcp.annotations.mcp_template_description:extendee -> google.protobuf.MessageOptions
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	0,  // [0:23] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protogen_mcp_annotations_proto_init() }
func file_internal_protogen_mcp_annotations_proto_init() {
	if File_internal_protogen_mcp_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protogen_mcp_annotations_proto_rawDesc), len(file_internal_protogen_mcp_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 23,
			NumServices:   0,
		},
		GoTypes:           file_internal_protogen_mcp_annotations_proto_goTypes,
		DependencyIndexes: file_internal_protogen_mcp_annotations_proto_depIdxs,
		ExtensionInfos:    file_internal_protogen_mcp_annotations_proto_extTypes,
	}.Build()
	File_internal_protogen_mcp_annotations_proto = out.File
	file_internal_protogen_mcp_annotations_proto_goTypes = nil
	file_internal_protogen_mcp_annotations_proto_depIdxs = nil
}
