// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: examples/helloworld/helloworld.proto

package helloworld

import (
	_ "github.com/omrikiei/protoc-gen-mcp/internal/protogen/mcp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the person to greet
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The language to use for the greeting
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Whether to use formal greeting
	Formal bool `protobuf:"varint,3,opt,name=formal,proto3" json:"formal,omitempty"`
	// The number of times to repeat the greeting
	Repeat        int32 `protobuf:"varint,4,opt,name=repeat,proto3" json:"repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_examples_helloworld_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_helloworld_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_examples_helloworld_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *HelloRequest) GetFormal() bool {
	if x != nil {
		return x.Formal
	}
	return false
}

func (x *HelloRequest) GetRepeat() int32 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

// The response message containing the greeting
type HelloReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The greeting message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Progress information
	CurrentRepeat   int32   `protobuf:"varint,2,opt,name=current_repeat,json=currentRepeat,proto3" json:"current_repeat,omitempty"`
	TotalRepeats    int32   `protobuf:"varint,3,opt,name=total_repeats,json=totalRepeats,proto3" json:"total_repeats,omitempty"`
	ProgressPercent float32 `protobuf:"fixed32,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_examples_helloworld_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_helloworld_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_examples_helloworld_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloReply) GetCurrentRepeat() int32 {
	if x != nil {
		return x.CurrentRepeat
	}
	return 0
}

func (x *HelloReply) GetTotalRepeats() int32 {
	if x != nil {
		return x.TotalRepeats
	}
	return 0
}

func (x *HelloReply) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

var File_examples_helloworld_helloworld_proto protoreflect.FileDescriptor

const file_examples_helloworld_helloworld_proto_rawDesc = "" +
	"\n" +
	"$examples/helloworld/helloworld.proto\x12\n" +
	"helloworld\x1a'internal/protogen/mcp/annotations.proto\"\x85\x03\n" +
	"\fHelloRequest\x12\x8c\x01\n" +
	"\x04name\x18\x01 \x01(\tBx\x80\xb5\x18\x01\x88\xb5\x18\x01\xaa\xb5\x18\x14^[a-zA-Z0-9_]{3,50}$\xb2\xb5\x18TName must be 3-50 characters long and contain only letters, numbers, and underscoresR\x04name\x12^\n" +
	"\blanguage\x18\x02 \x01(\tBB\x88\xb5\x18\x01\xaa\xb5\x18\x0f^(en|es|fr|de)$\xb2\xb5\x18'Language must be one of: en, es, fr, deR\blanguage\x12\x1c\n" +
	"\x06formal\x18\x03 \x01(\bB\x04\x88\xb5\x18\x01R\x06formal\x12V\n" +
	"\x06repeat\x18\x04 \x01(\x05B>\x88\xb5\x18\x01\xaa\xb5\x18\r^[1-9][0-9]?$\xb2\xb5\x18%Repeat count must be between 1 and 99R\x06repeat:\x10\x9a\xb5\x18\x04user\xa2\xb5\x18\x04read\"\x9d\x01\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x0ecurrent_repeat\x18\x02 \x01(\x05R\rcurrentRepeat\x12#\n" +
	"\rtotal_repeats\x18\x03 \x01(\x05R\ftotalRepeats\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x02R\x0fprogressPercent2\xd7\x03\n" +
	"\aGreeter\x12~\n" +
	"\bSayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"@\x80\xb5\x18\x01\x8a\xb5\x18#Sends a simple greeting to the user\x92\xb5\x18\tSay Hello\x98\xb5\x18\x01\xa8\xb5\x18\x01\x12\xa0\x01\n" +
	"\x11SayHelloWithQuery\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"Y\x80\xb5\x18\x01\x8a\xb5\x181Sends a greeting with additional query parameters\x92\xb5\x18\x14Say Hello with Query\x98\xb5\x18\x01\xa8\xb5\x18\x01\x12\x91\x01\n" +
	"\x0fStreamGreetings\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"J\x80\xb5\x18\x01\x8a\xb5\x18&Streams multiple greetings to the user\x92\xb5\x18\x10Stream Greetings\x98\xb5\x18\x01\xa8\xb5\x18\x010\x01\x1a\x15\x80\xb5\x18\x01\x8a\xb5\x18\x02v1\x92\xb5\x18\agreeterB8Z6github.com/omrikiei/protoc-gen-mcp/examples/helloworldb\x06proto3"

var (
	file_examples_helloworld_helloworld_proto_rawDescOnce sync.Once
	file_examples_helloworld_helloworld_proto_rawDescData []byte
)

func file_examples_helloworld_helloworld_proto_rawDescGZIP() []byte {
	file_examples_helloworld_helloworld_proto_rawDescOnce.Do(func() {
		file_examples_helloworld_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_helloworld_helloworld_proto_rawDesc), len(file_examples_helloworld_helloworld_proto_rawDesc)))
	})
	return file_examples_helloworld_helloworld_proto_rawDescData
}

var file_examples_helloworld_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_helloworld_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: helloworld.HelloRequest
	(*HelloReply)(nil),   // 1: helloworld.HelloReply
}
var file_examples_helloworld_helloworld_proto_depIdxs = []int32{
	0, // 0: helloworld.Greeter.SayHello:input_type -> helloworld.HelloRequest
	0, // 1: helloworld.Greeter.SayHelloWithQuery:input_type -> helloworld.HelloRequest
	0, // 2: helloworld.Greeter.StreamGreetings:input_type -> helloworld.HelloRequest
	1, // 3: helloworld.Greeter.SayHello:output_type -> helloworld.HelloReply
	1, // 4: helloworld.Greeter.SayHelloWithQuery:output_type -> helloworld.HelloReply
	1, // 5: helloworld.Greeter.StreamGreetings:output_type -> helloworld.HelloReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_helloworld_helloworld_proto_init() }
func file_examples_helloworld_helloworld_proto_init() {
	if File_examples_helloworld_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_helloworld_helloworld_proto_rawDesc), len(file_examples_helloworld_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_helloworld_helloworld_proto_goTypes,
		DependencyIndexes: file_examples_helloworld_helloworld_proto_depIdxs,
		MessageInfos:      file_examples_helloworld_helloworld_proto_msgTypes,
	}.Build()
	File_examples_helloworld_helloworld_proto = out.File
	file_examples_helloworld_helloworld_proto_goTypes = nil
	file_examples_helloworld_helloworld_proto_depIdxs = nil
}
