// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: examples/complex/complex.proto

package complex

import (
	_ "github.com/omrikiei/protoc-gen-mcp/internal/protogen/mcp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileId      string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	IncludeDetails bool                   `protobuf:"varint,3,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	MaxDepth       int32                  `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProfileRequest) Reset() {
	*x = UserProfileRequest{}
	mi := &file_examples_complex_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileRequest) ProtoMessage() {}

func (x *UserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileRequest.ProtoReflect.Descriptor instead.
func (*UserProfileRequest) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UserProfileRequest) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

func (x *UserProfileRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type UserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Avatar        []byte                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_examples_complex_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfileResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UserProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfileResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserProfileResponse) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type NestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Recursive     bool                   `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedRequest) Reset() {
	*x = NestedRequest{}
	mi := &file_examples_complex_complex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedRequest) ProtoMessage() {}

func (x *NestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedRequest.ProtoReflect.Descriptor instead.
func (*NestedRequest) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{2}
}

func (x *NestedRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *NestedRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *NestedRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *NestedRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type NestedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedResponse) Reset() {
	*x = NestedResponse{}
	mi := &file_examples_complex_complex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedResponse) ProtoMessage() {}

func (x *NestedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedResponse.ProtoReflect.Descriptor instead.
func (*NestedResponse) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{3}
}

func (x *NestedResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *NestedResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *NestedResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *NestedResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NestedResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filters        []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,5,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	SortBy         string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDesc       bool                   `protobuf:"varint,7,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_examples_complex_complex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

func (x *SearchRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type SearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Resources       []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	TotalCount      int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page            int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ProgressPercent float32                `protobuf:"fixed32,5,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_examples_complex_complex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SearchResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResponse) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Content       []byte                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_examples_complex_complex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{6}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Resource) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Resource) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Resource) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_examples_complex_complex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_complex_complex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_examples_complex_complex_proto_rawDescGZIP(), []int{7}
}

func (x *UploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_examples_complex_complex_proto protoreflect.FileDescriptor

const file_examples_complex_complex_proto_rawDesc = "" +
	"\n" +
	"\x1eexamples/complex/complex.proto\x12\acomplex\x1a'internal/protogen/mcp/annotations.proto\"\xe1\x01\n" +
	"\x12UserProfileRequest\x12f\n" +
	"\auser_id\x18\x01 \x01(\tBM\x80\xb5\x18\x01\xaa\xb5\x18E^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$R\x06userId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12'\n" +
	"\x0finclude_details\x18\x03 \x01(\bR\x0eincludeDetails\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\x05R\bmaxDepth\"\xef\x02\n" +
	"\x13UserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.complex.UserProfileResponse.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\fR\x06avatar\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:Y\x80\xb5\x18\x01\x8a\xb5\x18/complex://users/{user_id}/profiles/{profile_id}\x92\xb5\x18\x1eUser profile resource template\"\x92\x01\n" +
	"\rNestedRequest\x12\x1b\n" +
	"\x06org_id\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x05orgId\x12\x1d\n" +
	"\ateam_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06teamId\x12!\n" +
	"\tmember_id\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\bmemberId\x12\"\n" +
	"\trecursive\x18\x04 \x01(\bB\x04\x88\xb5\x18\x01R\trecursive\"\xec\x01\n" +
	"\x0eNestedResponse\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions:C\x80\xb5\x18\x01\x8a\xb5\x18;complex://orgs/{org_id}/teams/{team_id}/members/{member_id}\"\x9b\x02\n" +
	"\rSearchRequest\x12\x1a\n" +
	"\x05query\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\x05query\x12)\n" +
	"\x04page\x18\x02 \x01(\x05B\x15\x88\xb5\x18\x01\xaa\xb5\x18\r^[1-9][0-9]*$R\x04page\x122\n" +
	"\tpage_size\x18\x03 \x01(\x05B\x15\x88\xb5\x18\x01\xaa\xb5\x18\r^[1-9][0-9]*$R\bpageSize\x12\x1e\n" +
	"\afilters\x18\x04 \x03(\tB\x04\x88\xb5\x18\x01R\afilters\x12-\n" +
	"\x0finclude_deleted\x18\x05 \x01(\bB\x04\x88\xb5\x18\x01R\x0eincludeDeleted\x12\x1d\n" +
	"\asort_by\x18\x06 \x01(\tB\x04\x88\xb5\x18\x01R\x06sortBy\x12!\n" +
	"\tsort_desc\x18\a \x01(\bB\x04\x88\xb5\x18\x01R\bsortDesc\"\xbe\x01\n" +
	"\x0eSearchResponse\x12/\n" +
	"\tresources\x18\x01 \x03(\v2\x11.complex.ResourceR\tresources\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12)\n" +
	"\x10progress_percent\x18\x05 \x01(\x02R\x0fprogressPercent\"\xf3\x02\n" +
	"\bResource\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12;\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1f.complex.Resource.MetadataEntryR\bmetadata\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\acontent\x18\b \x01(\fR\acontent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:=\x80\xb5\x18\x01\x8a\xb5\x18\x18complex://resources/{id}\x92\xb5\x18\x19Generic resource template\"\xec\x01\n" +
	"\rUploadRequest\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xaa\xb5\x18\x16^[a-zA-Z0-9_-]{1,100}$R\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.complex.UploadRequest.MetadataEntryR\bmetadata\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x80\x05\n" +
	"\x0eComplexService\x12\x97\x01\n" +
	"\x0eGetUserProfile\x12\x1b.complex.UserProfileRequest\x1a\x1c.complex.UserProfileResponse\"J\x80\xb5\x18\x01\x8a\xb5\x18&Retrieves a user's profile information\x92\xb5\x18\x10Get User Profile\x98\xb5\x18\x01\xa8\xb5\x18\x01\x12\x94\x01\n" +
	"\x11GetNestedResource\x12\x16.complex.NestedRequest\x1a\x17.complex.NestedResponse\"L\x80\xb5\x18\x01\x8a\xb5\x18%Retrieves nested resource information\x92\xb5\x18\x13Get Nested Resource\x98\xb5\x18\x01\xa8\xb5\x18\x010\x01\x12\x95\x01\n" +
	"\x0fSearchResources\x12\x16.complex.SearchRequest\x1a\x17.complex.SearchResponse\"Q\x80\xb5\x18\x01\x8a\xb5\x18-Searches for resources with complex filtering\x92\xb5\x18\x10Search Resources\x98\xb5\x18\x01\xa8\xb5\x18\x01\x12\x8a\x01\n" +
	"\x0eUploadResource\x12\x16.complex.UploadRequest\x1a\x11.complex.Resource\"M\x80\xb5\x18\x01\x8a\xb5\x18*Uploads a new resource with binary content\x92\xb5\x18\x0fUpload Resource\xa0\xb5\x18\x01\xb0\xb5\x18\x01\x1a\x18\x80\xb5\x18\x01\x8a\xb5\x18\x02v1\xa2\xb5\x18\n" +
	"complex://B5Z3github.com/omrikiei/protoc-gen-mcp/examples/complexb\x06proto3"

var (
	file_examples_complex_complex_proto_rawDescOnce sync.Once
	file_examples_complex_complex_proto_rawDescData []byte
)

func file_examples_complex_complex_proto_rawDescGZIP() []byte {
	file_examples_complex_complex_proto_rawDescOnce.Do(func() {
		file_examples_complex_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_complex_complex_proto_rawDesc), len(file_examples_complex_complex_proto_rawDesc)))
	})
	return file_examples_complex_complex_proto_rawDescData
}

var file_examples_complex_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_examples_complex_complex_proto_goTypes = []any{
	(*UserProfileRequest)(nil),  // 0: complex.UserProfileRequest
	(*UserProfileResponse)(nil), // 1: complex.UserProfileResponse
	(*NestedRequest)(nil),       // 2: complex.NestedRequest
	(*NestedResponse)(nil),      // 3: complex.NestedResponse
	(*SearchRequest)(nil),       // 4: complex.SearchRequest
	(*SearchResponse)(nil),      // 5: complex.SearchResponse
	(*Resource)(nil),            // 6: complex.Resource
	(*UploadRequest)(nil),       // 7: complex.UploadRequest
	nil,                         // 8: complex.UserProfileResponse.MetadataEntry
	nil,                         // 9: complex.Resource.MetadataEntry
	nil,                         // 10: complex.UploadRequest.MetadataEntry
}
var file_examples_complex_complex_proto_depIdxs = []int32{
	8,  // 0: complex.UserProfileResponse.metadata:type_name -> complex.UserProfileResponse.MetadataEntry
	6,  // 1: complex.SearchResponse.resources:type_name -> complex.Resource
	9,  // 2: complex.Resource.metadata:type_name -> complex.Resource.MetadataEntry
	10, // 3: complex.UploadRequest.metadata:type_name -> complex.UploadRequest.MetadataEntry
	0,  // 4: complex.ComplexService.GetUserProfile:input_type -> complex.UserProfileRequest
	2,  // 5: complex.ComplexService.GetNestedResource:input_type -> complex.NestedRequest
	4,  // 6: complex.ComplexService.SearchResources:input_type -> complex.SearchRequest
	7,  // 7: complex.ComplexService.UploadResource:input_type -> complex.UploadRequest
	1,  // 8: complex.ComplexService.GetUserProfile:output_type -> complex.UserProfileResponse
	3,  // 9: complex.ComplexService.GetNestedResource:output_type -> complex.NestedResponse
	5,  // 10: complex.ComplexService.SearchResources:output_type -> complex.SearchResponse
	6,  // 11: complex.ComplexService.UploadResource:output_type -> complex.Resource
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_examples_complex_complex_proto_init() }
func file_examples_complex_complex_proto_init() {
	if File_examples_complex_complex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_complex_complex_proto_rawDesc), len(file_examples_complex_complex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_complex_complex_proto_goTypes,
		DependencyIndexes: file_examples_complex_complex_proto_depIdxs,
		MessageInfos:      file_examples_complex_complex_proto_msgTypes,
	}.Build()
	File_examples_complex_complex_proto = out.File
	file_examples_complex_complex_proto_goTypes = nil
	file_examples_complex_complex_proto_depIdxs = nil
}
