// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: mcp/service.proto

package mcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPRequest represents a generic MCP request
type MCPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request metadata
	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The request body
	Body          []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPRequest) Reset() {
	*x = MCPRequest{}
	mi := &file_mcp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPRequest) ProtoMessage() {}

func (x *MCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPRequest.ProtoReflect.Descriptor instead.
func (*MCPRequest) Descriptor() ([]byte, []int) {
	return file_mcp_service_proto_rawDescGZIP(), []int{0}
}

func (x *MCPRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MCPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// MCPResponse represents a generic MCP response
type MCPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The response metadata
	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The response body
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// The response status code
	StatusCode    int32 `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPResponse) Reset() {
	*x = MCPResponse{}
	mi := &file_mcp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPResponse) ProtoMessage() {}

func (x *MCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPResponse.ProtoReflect.Descriptor instead.
func (*MCPResponse) Descriptor() ([]byte, []int) {
	return file_mcp_service_proto_rawDescGZIP(), []int{1}
}

func (x *MCPResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MCPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MCPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

// MCPError represents an MCP error
type MCPError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// The error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The error details
	Details       map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPError) Reset() {
	*x = MCPError{}
	mi := &file_mcp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPError) ProtoMessage() {}

func (x *MCPError) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPError.ProtoReflect.Descriptor instead.
func (*MCPError) Descriptor() ([]byte, []int) {
	return file_mcp_service_proto_rawDescGZIP(), []int{2}
}

func (x *MCPError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MCPError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MCPError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_mcp_service_proto protoreflect.FileDescriptor

const file_mcp_service_proto_rawDesc = "" +
	"\n" +
	"\x11mcp/service.proto\x12\x03mcp\"\x98\x01\n" +
	"\n" +
	"MCPRequest\x129\n" +
	"\bmetadata\x18\x01 \x03(\v2\x1d.mcp.MCPRequest.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\vMCPResponse\x12:\n" +
	"\bmetadata\x18\x01 \x03(\v2\x1e.mcp.MCPResponse.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\bMCPError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\adetails\x18\x03 \x03(\v2\x1a.mcp.MCPError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B1Z/github.com/omrikiei/protoc-gen-mcp/protogen/mcpb\x06proto3"

var (
	file_mcp_service_proto_rawDescOnce sync.Once
	file_mcp_service_proto_rawDescData []byte
)

func file_mcp_service_proto_rawDescGZIP() []byte {
	file_mcp_service_proto_rawDescOnce.Do(func() {
		file_mcp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_service_proto_rawDesc), len(file_mcp_service_proto_rawDesc)))
	})
	return file_mcp_service_proto_rawDescData
}

var file_mcp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mcp_service_proto_goTypes = []any{
	(*MCPRequest)(nil),  // 0: mcp.MCPRequest
	(*MCPResponse)(nil), // 1: mcp.MCPResponse
	(*MCPError)(nil),    // 2: mcp.MCPError
	nil,                 // 3: mcp.MCPRequest.MetadataEntry
	nil,                 // 4: mcp.MCPResponse.MetadataEntry
	nil,                 // 5: mcp.MCPError.DetailsEntry
}
var file_mcp_service_proto_depIdxs = []int32{
	3, // 0: mcp.MCPRequest.metadata:type_name -> mcp.MCPRequest.MetadataEntry
	4, // 1: mcp.MCPResponse.metadata:type_name -> mcp.MCPResponse.MetadataEntry
	5, // 2: mcp.MCPError.details:type_name -> mcp.MCPError.DetailsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mcp_service_proto_init() }
func file_mcp_service_proto_init() {
	if File_mcp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_service_proto_rawDesc), len(file_mcp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_service_proto_goTypes,
		DependencyIndexes: file_mcp_service_proto_depIdxs,
		MessageInfos:      file_mcp_service_proto_msgTypes,
	}.Build()
	File_mcp_service_proto = out.File
	file_mcp_service_proto_goTypes = nil
	file_mcp_service_proto_depIdxs = nil
}
