// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: test_annotations.proto

package test

import (
	_ "github.com/omrikiei/protoc-gen-mcp/protogen/mcp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *TestFilters           `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_test_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_test_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetFilters() *TestFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type TestFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestFilters) Reset() {
	*x = TestFilters{}
	mi := &file_test_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFilters) ProtoMessage() {}

func (x *TestFilters) ProtoReflect() protoreflect.Message {
	mi := &file_test_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFilters.ProtoReflect.Descriptor instead.
func (*TestFilters) Descriptor() ([]byte, []int) {
	return file_test_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *TestFilters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestFilters) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TestFilters) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_test_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_test_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *TestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_test_annotations_proto protoreflect.FileDescriptor

const file_test_annotations_proto_rawDesc = "" +
	"\n" +
	"\x16test_annotations.proto\x12\x04test\x1a\x15mcp/annotations.proto\"e\n" +
	"\vTestRequest\x12V\n" +
	"\afilters\x18\x01 \x01(\v2\x11.test.TestFiltersB)\x9a\xb5\x18!Test filters with detailed schema\xb8\xb5\x18\x01R\afilters\"\x94\x01\n" +
	"\vTestFilters\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\x9a\xb5\x18\vName filter\xb8\xb5\x18\x01R\x04name\x123\n" +
	"\bcategory\x18\x02 \x01(\tB\x17\x9a\xb5\x18\x0fCategory filter\xb8\xb5\x18\x01R\bcategory\x12'\n" +
	"\x04tags\x18\x03 \x03(\tB\x13\x9a\xb5\x18\vTags filter\xb8\xb5\x18\x01R\x04tags\"&\n" +
	"\fTestResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2O\n" +
	"\vTestService\x126\n" +
	"\aTestRPC\x12\x11.test.TestRequest\x1a\x12.test.TestResponse\"\x04\xb0\xb5\x18\x01\x1a\b\x8a\xb5\x18\x04toolB3Z1github.com/mark3labs/protoc-gen-mcp/examples/testb\x06proto3"

var (
	file_test_annotations_proto_rawDescOnce sync.Once
	file_test_annotations_proto_rawDescData []byte
)

func file_test_annotations_proto_rawDescGZIP() []byte {
	file_test_annotations_proto_rawDescOnce.Do(func() {
		file_test_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_annotations_proto_rawDesc), len(file_test_annotations_proto_rawDesc)))
	})
	return file_test_annotations_proto_rawDescData
}

var file_test_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_annotations_proto_goTypes = []any{
	(*TestRequest)(nil),  // 0: test.TestRequest
	(*TestFilters)(nil),  // 1: test.TestFilters
	(*TestResponse)(nil), // 2: test.TestResponse
}
var file_test_annotations_proto_depIdxs = []int32{
	1, // 0: test.TestRequest.filters:type_name -> test.TestFilters
	0, // 1: test.TestService.TestRPC:input_type -> test.TestRequest
	2, // 2: test.TestService.TestRPC:output_type -> test.TestResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_annotations_proto_init() }
func file_test_annotations_proto_init() {
	if File_test_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_annotations_proto_rawDesc), len(file_test_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_annotations_proto_goTypes,
		DependencyIndexes: file_test_annotations_proto_depIdxs,
		MessageInfos:      file_test_annotations_proto_msgTypes,
	}.Build()
	File_test_annotations_proto = out.File
	file_test_annotations_proto_goTypes = nil
	file_test_annotations_proto_depIdxs = nil
}
